# Generated by Django 4.2.1 on 2023-05-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('grade', models.IntegerField()),
                ('number', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
