# Generated by Django 4.2.1 on 2023-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('salary', models.IntegerField()),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
