# Generated by Django 4.2.1 on 2023-05-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('studentId', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
