# Generated by Django 4.2.1 on 2023-05-30 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_movie_created_at_movie_updated_at_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movieApp.movie'),
        ),
    ]
